server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: FishPic-backend
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 一次请求总大小
      max-request-size: 100MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FishPics
    username: # 数据库账号
    password: # 数据库密码
  data:
    redis:
      host: # redis 地址
      database: 0
      port: 6379
  profiles: # 使用本地环境配置文件
    active: local
# SpringAIAlibaba 配置
#  ai:
#    dashscope:
#      api-key: # 阿里云灵积 api-key

# 自定义大模型名称配置
modal:
  tagModal: qwen-vl-flash # ai 自动打图片标签
  textModal: qwen3-vl-plus  # ai 自动图片描述
  baseImageModal: qwen-image-2.0  # ai 基础图片编辑（普通用户）
  VIPImageModal: qwen-image-2.0-pro # ai VIP高清编辑（专业级）

knife4j:
  enable: true
  openapi:
    title: fish图库测试文档
    description: "fish图库测试文档"
    email: 3057433102@qq.com
    concat: fish
    version: v0.5
    group:
      test:
        group-name: 开发测试
        api-rule: package
        api-rule-resources:
          - hk.ljx.fishpicsbackend.user
          - hk.ljx.fishpicsbackend.post
          - hk.ljx.fishpicsbackend.picture
          - hk.ljx.fishpicsbackend.comment
          - hk.ljx.fishpicsbackend.space
          - hk.ljx.fishpicsbackend.system

# 腾讯云 COS 配置
#cos:
#  secretId:
#  secretKey:
#  region:
#  bucket:
#  public: true  # 开发true 生产false
#  url: # 腾讯云图片 url 前缀

logging:
  level:
    root: info
    # 业务包
    hk.ljx.fishpicsbackend: debug
    # MyBatis 打印 SQL
    org.mybatis: debug
    # Spring 打印执行的 SQL
    org.springframework.jdbc.core: debug